export const rows = [
    {
      id: 1,
      title: "Academy Dinosaur",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "NC-17",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 2,
      title: "jab we met",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 3,
      title: "fast and furious",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 4,
      title: "the social dillema",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 5,
      title: "titanic",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 6,
      title: "test",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 7,
      title: "the social dillema",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 8,
      title: "the social dillema",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    {
      id: 9,
      title: "the social dillema",
      description: "This is a movie",
      releaseYear: 2009,
      language: "English",
      director: "Nolan",
      rating: "PG",
      specialFeatures: "Deleted Scenes",
    },
    

  
  ];
export default rows;